### PR TITLE
Add NNRW and NSDI to gaTable.yaml

### PR DESCRIPTION
**Pull request by mwernimont**
#57

### CODE REVIEW

**Comment by mwernimont** [comment]
Screen Shot 2019-06-21 at 12 28 55 PM
Screen Shot 2019-06-21 at 12 29 23 PM

**Comment by mwernimont** [comment]
Awe yeah!

**Comment by mwernimont** [comment]
Shoot, USGS USGS Water Resources NSDI Node might not be?

**Comment by mwernimont** [comment]
Screen Shot 2019-06-21 at 12 35 01 PM
Nevermind

**Comment by wdwatkins** [comment]
Nah that's fine, it didn't have google analytics until a few weeks ago, so there isn't much data.

**Pull request merged**
