### PR TITLE
Style stuff

### PR DESCRIPTION
**Pull request by ldecicco-USGS**

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
I might still play around with the "traffic" label placement...but here's where that first graph stands:

image

**Comment by ldecicco-USGS** [comment]
Here's the portfolio other stuff:

image

**Comment by ldecicco-USGS** [comment]
And project stuff:

image

**Comment by eread-usgs** [comment]
@ldecicco-USGS this layout looks significantly improved- really nice!! Based on these screenshots I only have a couple of minor comments;

1) On the top figure from the summary page: The new users/ returning users distinction doesn't look *quite* as clear to my eyes as I remember it from prior versions. Could the skinny line be a little skinnier?

2) Under traffic sources: can you wrap the text on anything over 12 (ish?) characters so that the graph layout is not dominated by whatever the longest traffic source name is?

**Comment by ldecicco-USGS** [comment]
Merging to see on dev

**Pull request merged**
