### PR TITLE
Move legend

### PR DESCRIPTION
**Pull request by ldecicco-USGS**

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
portfolio_sessions_all

**Comment by ldecicco-USGS** [comment]
I was worried that there's be a rabbit hole to climb down if we tried to dynamically adjust the legend placement by purely shifting vertically in a single facet box (ie..low traffic / weekly). Moving to monthly data is a quick fix to an already rare issue. Weekly data could be more noisy when there are viral pages, hence moving to the monthly view should alleviate this (mostly).

We could do even more by checking the xmin limits of the legend box with the xmax of the data on those same y's, and if there's an overlap, move the legend up. Then...recheck. If on recheck there's still an overlap, switch to weekly or yearly data, recheck.  

Another option is to put it in yearly data which is even less noisy. This issue with this is that the traffic labels are already in that column. There was push-back on moving the traffic labels to monthly or weekly because the actual calculations to determine what bin the apps should be takes place on the yearly data.

Yet another option.....Adjust the x axis limits so that if there is an overlap, the legend scoots horizontally, by staying in the same lower right corner.

A few more options:
2 or 3 little legends? Just "Total Sessions" and "New Users" in the monthly column. A legend with a title "Trend" that then just says "Up", "Down","None" (this would be skinnier and could be in the weekly column). The "Missing" data line could be on it's own or baked into the Sessions/Users. To be super-duper careful, we could do this with the dynamic vertical line adjustment described above.

We could move the legend below the graph. I generally don't think a long skinny legend look as nice, but it's certainly an option.

 Any strong opinions on one of these?

**Comment by eread-usgs** [comment]
I vote for (2) for now @ldecicco-USGS

**Comment by eread-usgs** [comment]
I'm not hearing any major objections- lets do this!

**Comment by ldecicco-USGS** [comment]
We're going to merge this one for now, and explore #2 in the future.

**Pull request merged**
