### PR TITLE
Adding month to portfolio page

### PR DESCRIPTION
**Pull request by ldecicco-USGS**
We talked about possibly adding this in the retro. I was curious what the effort would be in ggplot2, and it wasn't bad. The biggest issues I didn't solve (didn't spend much time on it though)...was using the `geom_text` with a `hjust` (to skooch over the numbers) with `facet_grid`..the numbers would get cut off. It's OK, but there probably is a better way than what I've got here.

Anyway, we can take this or leave it in base, doesn't matter to me. We might end up scraping the whole thing and do a column of yearly sessions with a column of spark lines.

### CODE REVIEW

**Comment by jread-usgs** [comment]
Cool - that code is a lot cleaner! :+1: Posting the result here so people can see it w/o building from your branch:
portfolio_sessions_all

A couple of ideas/questions:

- I think we might want to remove the grids in this, since it makes it look like the axis aren't breaking for the different use categories and I'm not sure what values those grids are placed on (is it a uniform grid that isn't related to the scale?)
- Is it possible to add the thicker line that represented "new session" in the older version of the fig? Also, is it easy to place greater emphasis on the breaks between the usage categories?

I think you should ignore my comments above ☝️ if we aren't sure that we are using the fig, so maybe we can table

**Comment by eread-usgs** [comment]
@ldecicco-USGS  This looks good and there are a couple of things I'd like done to consider it finished and ready for more formal review outside of our group. I'm being really specific about these things now because we have so many loose end style issues- and I want to be sure ggplot for this will allow us to make the plot look the way we want it to. 

@jread-usgs I think we have consensus that this figure (or some form of it) *will* be used in the next iteration. The only other option we discussed, which we decided to table until you return and we can discuss in person altogether, is to use sparklines here to show temporal variability. In that case, we would likely only be able to include one time frame, e.g., just 'Year' and then sparklines next to that. 

The issues I bring up below would need to be resolved regardless of whether we drop down to just year and do sparklines, or if we keep it in its current form. 

1) make clearer distinction between low/moderate/high/very high traffic sections - this was done by using four differently shaded boxes on the first iteration of this- something like that, or just backgrounds with breaks between them would work as well. 
2) Prevent text/numbers running off of side of plot (e.g., CIDA year)
3) vertically orient labels for sections, OR (preferred) place them in the lower right hand corner of each section or just below each section. if they are just below each section, there would need to be a slightly larger space between each section. 
4) I agree that gridlines are not necessary b/c the value of each session count is shown.

**Comment by ldecicco-USGS** [comment]
portfolio_sessions_all

With a little more fiddling. I also mentioned in standup....I think I can pretty quickly turn this into 2 columns, 1 year sessions, 1 sparklines....so stay tuned...

**Comment by ldecicco-USGS** [comment]
I see @jread-usgs put the "high traffic" etc labels in the "Year"....that probably makes more sense...I'll shift those over too.

**Comment by eread-usgs** [comment]
+ add legend

**Comment by ldecicco-USGS** [comment]
I added a little legend via brute force. I'll play with the sparklines tonight....

portfolio_sessions_all


I'm coming back to this graph personally because when I took a quick look at the sparklines, all it really could tell us was that Viz Lab Water Use had a big spike. It'll take some finesse with de-sampling the data to get the graph useful enough to see anything more than that.

**Comment by jread-usgs** [comment]
Can the left margin between the start of the line segments and the box be removed?

**Comment by ldecicco-USGS** [comment]
That's been a thorn in my side...the answer I want to give you is no. 

If it's a deal-breaker, I can work on it, but not today. I do have another idea on how to make it work better (it's the multi-facet / negative href text running off the graph issue I was talking about above). 

Although, I've also started thinking the "white" space there isn't so bad (and I'm not just saying that to avoid doing the task...just that the white-space gives it a little less cluttered feel)

**Comment by ldecicco-USGS** [comment]
Lesson learned.....making a *positive* `hjust` helps!

portfolio_sessions_all


Anyway, we talked and we think this is merge-able...plus now I'll remember to make a branch :disappointed:

**Pull request merged**
