### PR TITLE
Legend with up/down

### PR DESCRIPTION
**Pull request by ldecicco-USGS**

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
Could someone with data in the last week actually pull this down an make sure the graph looks OK before merging? It's all kind of squushy without data.

**Comment by aappling-usgs** [comment]
i'm trying it

**Comment by aappling-usgs** [comment]
Yeah, looks nice on my computer. But we're seeing that font problem on Jenkins, so...

**Comment by ldecicco-USGS** [comment]
I'm going to try the Cairo package and see if that helps.

**Pull request merged**
