### PR TITLE
Converting tables to RDS

### PR DESCRIPTION
**Pull request by ldecicco-USGS**

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
@mwernimont will need to play with the style, but now we can pass in the time as text:

image

**Comment by mwernimont** [comment]
Awesome

**Comment by mwernimont** [comment]
@ldecicco-USGS question: Is the total time cutting off days or seconds in that example?

**Comment by ldecicco-USGS** [comment]
Good catch, it was getting taken off by mistake. Here's what it looks like now:

image

**Comment by mwernimont** [comment]
@eread-usgs Do we want it to all be in the 00:00:00:00 pattern?

**Comment by ldecicco-USGS** [comment]
Keep in mind (especially for the year calculations), there can be >1000 days...so it be confusing to see "1210:12:34:16". If I saw that..I'd have to stare at it awhile to figure out what that meant. We could also add a year number...: "3 years, 117:12:34:16"....or "3 years, 117 days, 12:34:16", or "03:117:12:34:16"....

We could also intelligently round. so the above example would be "3 years, 117 days" (ignoring the 12 hours 34 minutes etc). Maybe less than a total year include the hours/minutes? Less than a day include seconds?

**Comment by eread-usgs** [comment]
I agree w @ldecicco-USGS that we need to be intelligent about the way we show this stuff. @ldecicco-USGS how difficult is that to implement? Still hoping to get this thing out yet this week....

**Comment by ldecicco-USGS** [comment]
@jiwalker-usgs the ball's in your court now. The processes are spitting out rds lists:

```
> x <- readRDS("cache/process/83660223_time_year.rds")
> x
$total
  Years Days Hours Minutes Seconds
2     3  334    13      17      56

$ave
  Years Days Hours Minutes Seconds
1     0    0    00      01      55
```

**Pull request merged**
