### PR TITLE
restacked stickybar

### PR DESCRIPTION
**Pull request by mwernimont**
Return to summary and the project toggle buttons are now on top of the year, month, and week buttons at all times.  Return to summary is now blue for emphasis.

### CODE REVIEW

**Comment by jread-usgs** [comment]
@mwernimont can you put a screencap in as a comment

**Comment by mwernimont** [comment]
screen shot 2017-07-17 at 11 51 40 am

**Comment by jread-usgs** [comment]
Can we make some tweaks @mwernimont ? A couple of thoughts:

1. Seems confusing to have "return to summary" highlighted in the same way as the current time period. Perhaps it can be a different button type but not look exactly the same?
2. Can the "return" "previous" "next" be above the title and text (separated from the other toggle?

**Comment by mwernimont** [comment]
@jread-usgs So you don't want the return to summary and previous to be a part of the sticky and have to scroll up to the top each time you want to change the project or go back? I thought that would be annoying but can do that if you prefer it.

**Comment by mwernimont** [comment]
But I do get them being right next to each other is cluttering up what a user is supposed to be using...I will rethink this.

**Comment by jread-usgs** [comment]
Thanks Marty. Let me know if you have ideas

**Comment by aappling-usgs** [comment]
i'm a little late to this party, so maybe this has already been suggested...but what about putting the Return to Summary, Previous Application, and Next Application buttons at the top of the nav bar on the left rather than toward the middle of the screen?

image

**Comment by jread-usgs** [comment]
Seems like a clean solution to me!

**Comment by mwernimont** [comment]
screen shot 2017-07-18 at 12 35 05 pm

@jread-usgs I know you said you wanted them all on one line, but you would either have to change the text of the buttons or make the text tiny to accomplish this. I think this looks pretty good though.

**Comment by jread-usgs** [comment]
looks good to me :+1:

**Pull request merged**
